baseURL = 'https://wiki.pika-os.com/'
languageCode = 'en-gb'
title = 'PikaOS Wiki'
theme = 'compose'
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS","JSON"]

[params]
metaThemeColor = "#123456"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode
defaultLightingMode = "dark" # other possible values: "dark", "light"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 20

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = true

[search]
on = true
global = true # turn to `true` to enable global search
[search.algolia]
enable = false # if false search will default to fusejs
id = "Q40WQQX84U" # Application ID
index = "compose" # Index name
key = "da87401a458102ec6bbd6cc5e5cf8d95" # Search-Only API Key

# Site logo
[logo]
  lightMode = "images/compose.svg"
  darkMode = "images/compose-light.svg"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/onweru/compose/"